#!/bin/bash
#-------------------------------------------------------------------------------------------                                                                   
#-------------------------------------------------------------------------------------------

# 脚本变量
DST_conf_dirname="DoNotStarveTogether"   
DST_conf_basedir="$HOME/.klei" 
DST_bin_cmd="./dontstarve_dedicated_server_nullrenderer"   

function PreLibrary()
{
	sudo apt -y update
	sudo apt -y install screen lib32gcc1 lib32stdc++6 libcurl4-gnutls-dev:i386 htop diffutils grep p7zip
}

function update_game()
{
    if [ ! -d "./steamcmd" ];then
   	    PreLibrary
	    mkdir ./steamcmd
        cd ./steamcmd
        wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
        tar -xvzf steamcmd_linux.tar.gz
        rm -f steamcmd_linux.tar.gz
		cd $HOME
	fi
	cd ./steamcmd
	   ./steamcmd.sh +@ShutdownOnFailedCommand 1 +@NoPromptForPassword 1 +login anonymous +force_install_dir "$HOME/Steam/steamapps/common/DST_Public" +app_update 343050 validate +quit
	cd $HOME
	echo "服务器安装成功！"
}
#-beta returnofthembeta
function closeserver()
{
    if [[ $(screen -ls | grep -c "DST_Master") > 0 || $(screen -ls | grep -c "DST_Caves") > 0 ]]; then
	    if [[ $(screen -ls | grep -c "DST_Master") > 0 ]]; then
            screen -S "DST_Master" -p 0 -X stuff "c_shutdown(true)$(printf \\r)"
	    fi
	    if [[ $(screen -ls | grep -c "DST_Caves") > 0 ]]; then
            screen -S "DST_Caves" -p 0 -X stuff "c_shutdown(true)$(printf \\r)"
	    fi
	    sleep 10
	    echo -e "\e[92m服务器已关闭！\e[0m"
	else
	    echo "游戏服务器未开启！"
	fi
}

function startserver()
{
echo -e "\e[92m已有存档：\e[0m"
		ls -l ${DST_conf_basedir}/${DST_conf_dirname} |awk '/^d/ {print $NF}'
		echo -e "\e[92m请输入已有存档名称：（提示：在输入框右键鼠标可以粘贴。）\e[0m"
		read clustername
		cluster_name=$clustername
cd "$HOME/Steam/steamapps/common/DST_Public/bin"
	echo -e "\e[92m请选择要启动的服务器：1.仅地上  2.仅洞穴  3.地上 + 洞穴\e[0m"
	read shard 
	case $shard in
		1)		
		screen -dmS "DST_Master" /bin/sh -c "$DST_bin_cmd -console -conf_dir $DST_conf_dirname -cluster $cluster_name -shard Master"
		echo "#!/bin/bash
masterchatlog_path=\"${DST_conf_basedir}/${DST_conf_dirname}/${cluster_name}/Master/server_chat_log.txt\"
caveschatlog_path=\"${DST_conf_basedir}/${DST_conf_dirname}/${cluster_name}/Caves/server_chat_log.txt\"			
echo \"\" > \"$HOME/Steam/steamapps/common/DST_Public/mods/dedicated_server_mods_setup.lua\"	
cd $HOME/Steam/steamapps/common/DST_Public/bin
screen -dmS \"DST_Master\" /bin/sh -c \"$DST_bin_cmd -console -conf_dir $DST_conf_dirname -cluster $cluster_name -shard Master\"
echo -e \"\e[92m正在重启服务器。。。请稍后。。。\e[0m\"
sleep 60" > $HOME/rebootserver.sh
        echo 'if [[ $(screen -ls | grep -c "DST_Master") = 0 && $(screen -ls | grep -c "DST_Caves") > 0 ]]; then
    if [[ $(grep "Your Server Will Not Start !!!" -c "$masterchatlog_path") > 0 ]]; then
	    echo "服务器开启未成功，请执行关闭服务器命令后再次尝试，并注意令牌是否成功设置且有效。"
	else
		echo "服务器开启成功，和小伙伴尽情玩耍吧！"
    fi
else
	if [[ $(screen -ls | grep -c "DST_Master") > 0 ]]; then
        if [[ $(grep "Your Server Will Not Start !!!" -c "$masterchatlog_path") > 0 ]]; then
		    echo "服务器开启未成功，请执行关闭服务器命令后再次尝试，并注意令牌是否成功设置且有效。"
	    else
		    echo "服务器开启成功，和小伙伴尽情玩耍吧！"
		fi
	fi
	if [[ $(screen -ls | grep -c "DST_Caves") > 0 ]]; then
        if [[ $(grep "Your Server Will Not Start !!!" -c "$caveschatlog_path") > 0 ]]; then
		    echo "服务器开启未成功，请执行关闭服务器命令后再次尝试，并注意令牌是否成功设置且有效。"
	    else
		    echo "服务器开启成功，和小伙伴尽情玩耍吧！"
	    fi
	fi
fi' >> $HOME/rebootserver.sh
		;;
		2)
		screen -dmS "DST_Caves" /bin/sh -c "$DST_bin_cmd -console -conf_dir $DST_conf_dirname -cluster $cluster_name -shard Caves"
		echo "#!/bin/bash
masterchatlog_path=\"${DST_conf_basedir}/${DST_conf_dirname}/${cluster_name}/Master/server_chat_log.txt\"
caveschatlog_path=\"${DST_conf_basedir}/${DST_conf_dirname}/${cluster_name}/Caves/server_chat_log.txt\"
echo \"\" > \"$HOME/Steam/steamapps/common/DST_Public/mods/dedicated_server_mods_setup.lua\"		
cd $HOME/Steam/steamapps/common/DST_Public/bin
screen -dmS \"DST_Caves\" /bin/sh -c \"$DST_bin_cmd -console -conf_dir $DST_conf_dirname -cluster $cluster_name -shard Caves\"
echo -e \"\e[92m正在重启服务器。。。请稍后。。。\e[0m\"
sleep 60" > $HOME/rebootserver.sh
        echo 'if [[ $(screen -ls | grep -c "DST_Master") = 0 && $(screen -ls | grep -c "DST_Caves") > 0 ]]; then
    if [[ $(grep "Your Server Will Not Start !!!" -c "$masterchatlog_path") > 0 ]]; then
	    echo "服务器开启未成功，请执行关闭服务器命令后再次尝试，并注意令牌是否成功设置且有效。"
	else
		echo "服务器开启成功，和小伙伴尽情玩耍吧！"
    fi
else
	if [[ $(screen -ls | grep -c "DST_Master") > 0 ]]; then
        if [[ $(grep "Your Server Will Not Start !!!" -c "$masterchatlog_path") > 0 ]]; then
		    echo "服务器开启未成功，请执行关闭服务器命令后再次尝试，并注意令牌是否成功设置且有效。"
	    else
		    echo "服务器开启成功，和小伙伴尽情玩耍吧！"
		fi
	fi
	if [[ $(screen -ls | grep -c "DST_Caves") > 0 ]]; then
        if [[ $(grep "Your Server Will Not Start !!!" -c "$caveschatlog_path") > 0 ]]; then
		    echo "服务器开启未成功，请执行关闭服务器命令后再次尝试，并注意令牌是否成功设置且有效。"
	    else
		    echo "服务器开启成功，和小伙伴尽情玩耍吧！"
	    fi
	fi
fi' >> $HOME/rebootserver.sh
		;;
		3)
		screen -dmS "DST_Master" /bin/sh -c "$DST_bin_cmd -console -conf_dir $DST_conf_dirname -cluster $cluster_name -shard Master"
		screen -dmS "DST_Caves" /bin/sh -c "$DST_bin_cmd -console -conf_dir $DST_conf_dirname -cluster $cluster_name -shard Caves"
		echo "#!/bin/bash
masterchatlog_path=\"${DST_conf_basedir}/${DST_conf_dirname}/${cluster_name}/Master/server_chat_log.txt\"
caveschatlog_path=\"${DST_conf_basedir}/${DST_conf_dirname}/${cluster_name}/Caves/server_chat_log.txt\"	
cd $HOME/Steam/steamapps/common/DST_Public/bin
screen -dmS \"DST_Master\" /bin/sh -c \"$DST_bin_cmd -console -conf_dir $DST_conf_dirname -cluster $cluster_name -shard Master\"
screen -dmS \"DST_Caves\" /bin/sh -c \"$DST_bin_cmd -console -conf_dir $DST_conf_dirname -cluster $cluster_name -shard Caves\"
echo -e \"\e[92m正在重启服务器。。。请稍后。。。\e[0m\"
sleep 60" > $HOME/rebootserver.sh
        echo 'if [[ $(screen -ls | grep -c "DST_Master") = 0 && $(screen -ls | grep -c "DST_Caves") > 0 ]]; then
    if [[ $(grep "Your Server Will Not Start !!!" -c "$masterchatlog_path") > 0 ]]; then
	    echo "服务器开启未成功，请执行关闭服务器命令后再次尝试，并注意令牌是否成功设置且有效。"
	else
		echo "服务器开启成功，和小伙伴尽情玩耍吧！"
    fi
else
	if [[ $(screen -ls | grep -c "DST_Master") > 0 ]]; then
        if [[ $(grep "Your Server Will Not Start !!!" -c "$masterchatlog_path") > 0 ]]; then
		    echo "服务器开启未成功，请执行关闭服务器命令后再次尝试，并注意令牌是否成功设置且有效。"
	    else
		    echo "服务器开启成功，和小伙伴尽情玩耍吧！"
		fi
	fi
	if [[ $(screen -ls | grep -c "DST_Caves") > 0 ]]; then
        if [[ $(grep "Your Server Will Not Start !!!" -c "$caveschatlog_path") > 0 ]]; then
		    echo "服务器开启未成功，请执行关闭服务器命令后再次尝试，并注意令牌是否成功设置且有效。"
	    else
		    echo "服务器开启成功，和小伙伴尽情玩耍吧！"
	    fi
	fi
fi' >> $HOME/rebootserver.sh
		;;
	esac
	chmod u+x $HOME/rebootserver.sh
	echo -e "\e[92m服务器开启中。。。请稍候。。。\e[0m"
	sleep 60
	startcheck
	menu
}

function startcheck()
{
	if [[ $(screen -ls | grep -c "DST_Master") = 0 && $(screen -ls | grep -c "DST_Caves") > 0 ]]; then
        if [[ $(grep "Your Server Will Not Start !!!" -c "${DST_conf_basedir}/${DST_conf_dirname}/${cluster_name}/Master/server_chat_log.txt") > 0 ]]; then
		    echo "服务器开启未成功，请执行关闭服务器命令后再次尝试，并注意令牌是否成功设置且有效。"
	    else
		    echo "服务器开启成功，和小伙伴尽情玩耍吧！"
		fi
	else
	    if [[ $(screen -ls | grep -c "DST_Master") > 0 ]]; then
            if [[ $(grep "Your Server Will Not Start !!!" -c "${DST_conf_basedir}/${DST_conf_dirname}/${cluster_name}/Master/server_chat_log.txt") > 0 ]]; then
		        echo "服务器开启未成功，请执行关闭服务器命令后再次尝试，并注意令牌是否成功设置且有效。"
	        else
		        echo "服务器开启成功，和小伙伴尽情玩耍吧！"
		    fi
	    fi
	    if [[ $(screen -ls | grep -c "DST_Caves") > 0 ]]; then
            if [[ $(grep "Your Server Will Not Start !!!" -c "${DST_conf_basedir}/${DST_conf_dirname}/${cluster_name}/Caves/server_chat_log.txt") > 0 ]]; then
		        echo "服务器开启未成功，请执行关闭服务器命令后再次尝试，并注意令牌是否成功设置且有效。"
	        else
		        echo "服务器开启成功，和小伙伴尽情玩耍吧！"
		    fi
	    fi
	fi
}

function checkserver()
{    
	if [[ $(screen -ls | grep -c "DST_Master") > 0 || $(screen -ls | grep -c "DST_Caves") > 0 ]]; then
	    echo -e "\e[92m即将跳转游戏服务器窗口，要退回本界面，在游戏服务器窗口按 ctrl+a+d 再执行脚本即可。\e[0m"
		sleep 3
	    if [[ $(screen -ls | grep -c "DST_Master") > 0 && $(screen -ls | grep -c "DST_Caves") > 0 ]]; then
	        screen -r DST_Master
	    fi
	    if [[ $(screen -ls | grep -c "DST_Master") > 0 && $(screen -ls | grep -c "DST_Caves") = 0 ]]; then
	        screen -r DST_Master
	    fi
	    if [[ $(screen -ls | grep -c "DST_Master") = 0 && $(screen -ls | grep -c "DST_Caves") > 0 ]]; then
	        screen -r DST_Caves
	    fi
	else
	    echo "游戏服务器未开启！"
		menu
	fi
}

function exitshell()
{
   clear
   cd $HOME
}

function console()
{
while :
    do
	    echo -e "\e[33m================欢迎使用饥荒联机版独立服务器脚本[Ubuntu-Steam]==================\e[0m"
        echo
        echo -e "\e[92m[1]输入控制台代码并执行          [0]返回主菜单\e[0m"  
        echo
        echo -e "\e[33m================================================================================\e[0m"
        echo -e "\e[92m请输入命令代号：\e[0m"
        read cmd  
		    case $cmd in
                1)
				echo -e "\e[92m请输入控制台指令：\e[0m"
				read cscmd
                if [[ $(screen -ls | grep -c "DST_Master") > 0 ]]; then   									        
	                screen -S "DST_Master" -p 0 -X stuff "$cscmd$(printf \\r)"	
	            fi
				tail -10 
				console
				break;;
				0)
				menu
				break;;
		    esac
	done
}

function rebootannounce()
{
    if [[ $(screen -ls | grep -c "DST_Master") > 0 ]]; then   									        
	    screen -S "DST_Master" -p 0 -X stuff "c_announce(\"服务器设置因做了改动需要重启，预计耗时三分钟，给你带来的不便还请谅解！\")$(printf \\r)"	
	fi
	if [[ $(screen -ls | grep -c "DST_Caves") > 0 ]]; then						        
		screen -S "DST_Caves" -p 0 -X stuff "c_announce(\"服务器设置因做了改动需要重启，预计耗时三分钟，给你带来的不便还请谅解！\")$(printf \\r)"
	fi
}

function openswap()
{
    sudo dd if=/dev/zero of=/swapfile bs=1M count=2048
    sudo mkswap /swapfile
    sudo swapon /swapfile
	sudo chmod 0646 /etc/fstab
    echo "/swapfile swap swap defaults 0 0" >> /etc/fstab
	clear
    echo -e "\e[92m虚拟内存已开启！\e[0m"
}
function modm()
{
	while :
    do
	    echo -e "\e[33m================mod管理==================\e[0m"
        echo
        echo -e "\e[92m[1]添加单独mod		[2]添加mod合集		[3]列出已添加的mod		[0]返回主菜单\e[0m"  
        echo
        echo -e "\e[33m================================================================================\e[0m"
        echo -e "\e[92m请输入命令代号：\e[0m"
        read cmd  
		    case $cmd in
                1)
				modm
				break;;
				2)
				modm
				break;;
				3)
				modm
				break;;
				0)
				menu
				break;;
		    esac
	done
	#ServerModCollectionSetup("379114180")
	#ServerModSetup("350811795")
}
function menu()
{    
    while :
    do
	    echo -e "\e[33m================欢迎使用饥荒联机版独立服务器脚本[Ubuntu-Steam]==================\e[0m"
		echo	
		echo -e "\e[31m首次使用请将本地电脑上的MOD上传到\e[0m"
		echo -e "\e[31m云服务器$HOME/Steam/steamapps/common/DST_*/mods目录下\e[0m"
		echo
        echo -e "\e[92m[0]安装及初始化服务器    [1]开启服务器           [2]关闭服务器\e[0m"  
        echo -e "\e[92m[3]重启服务器            [4]查看游戏服务器状态   [5]退出本脚本\e[0m"
		echo -e "\e[92m[6]控制台                [7]开启虚拟内存（单服务器开洞穴使用）\e[0m"
		echo -e "\e[92m[8]mod管理\e[0m"
        echo  
        echo -e "\e[33m================================================================================\e[0m"
        echo -e "\e[92m请输入命令代号：\e[0m"
        read cmd  
		    case $cmd in
			    0)
				update_game
				closeserver
				menu
				break;;
				1)
				startserver
				menu
				break;;
			    2)
				closeserver
				menu
                break;;
				3)
				rebootannounce
				sleep 10
				closeserver
				./rebootserver.sh
				menu
				break;;
			    4)
				checkserver
			    break;;
				5)
				exitshell
			    break;;
				6)
				console
				menu
				break;;
                7)
				openswap
				menu
			    break;;		
				8)
				modm
				menu
				break;;			
		    esac
    done
}
menu
